### ISSUE TITLE
Unexpected argument collision in single-argument branches

### ISSUE THREAD

**Issue by ZeroMemes** [Mojang/brigadier#39]
Consider the following command tree:
```java
dispatcher.register(literal("goal")
    .then(argument("y", integer())
        .executes(c -> {
            setGoal(new GoalYLevel(
                c.getArgument("y", Integer.class)
            ));
            return 0;
        })
    )
    .then(argument("x", integer())
        .then(argument("z", integer())
            .executes(c -> {
                setGoal(new GoalXZ(
                    c.getArgument("x", Integer.class),
                    c.getArgument("z", Integer.class)
                ));
                return 0;
            })
        )
    )
    .then(argument("x", integer())
        .then(argument("y", integer())
            .then(argument("z", integer())
                .executes(c -> {
                    setGoal(new GoalBlock(
                        c.getArgument("x", Integer.class),
                        c.getArgument("y", Integer.class),
                        c.getArgument("z", Integer.class)
                    ));
                    return 0;
                })
            )
        )
    )
);
```

This should have 3 possible usages
```
goal <y>
goal <x> <z>
goal <x> <y> <z>
```

However, when I try to execute the command with a single integer argument (via ``goal 1``) an exception is thrown!

```
com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown command at position 6: goal 1<--[HERE]
  at com.mojang.brigadier.exceptions.SimpleCommandExceptionType.createWithContext(SimpleCommandExceptionType.java:21)
  at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:283)
  at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:178)
  at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:143)
  ...
```

Both the 2-arg and 3-arg usages work as intended:
![Chat Output](https://i.imgur.com/KlPAPL3.png)

I have found that the only solution to this is to rename the argument in the single argument branch from ``y``.
I believe this issue relates to the comment made by [Dinnerbone](https://github.com/Dinnerbone) [Here](https://github.com/Mojang/brigadier/issues/32#issuecomment-429652104).

**Comment by Marcono1234** [comment]
It appears that one of the `x` nodes is choosen (see also @NeunEinser's [comment](https://github.com/Mojang/brigadier/issues/38#issuecomment-431802706)). This could possibly be solved (unless I missed something) by adding a check to the [sorting](https://github.com/Mojang/brigadier/blob/447845ba89c1285cff0178afef082339c93c0ba5/src/main/java/com/mojang/brigadier/CommandDispatcher.java#L407) to prefer nodes which do not have children in case the reader reached the end.

**Comment by GiantNuker** [comment]
There are 2 `x`es on the same level. Try this:
```java
dispatcher.register(literal("goal")
    .then(argument("y", integer())
        .executes(c -> {
            setGoal(new GoalYLevel(
                c.getArgument("y", Integer.class)
            ));
            return 0;
        })

    .then(argument("x", integer())
        .then(argument("z", integer())
            .executes(c -> {
                setGoal(new GoalXZ(
                    c.getArgument("x", Integer.class),
                    c.getArgument("z", Integer.class)
                ));
                return 0;
            })
        )
        .then(argument("y", integer())
            .then(argument("z", integer())
                .executes(c -> {
                    setGoal(new GoalBlock(
                        c.getArgument("x", Integer.class),
                        c.getArgument("y", Integer.class),
                        c.getArgument("z", Integer.class)
                    ));
                    return 0;
                })
            )
        )
    )
);```
